name: Build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '2.7'         
    
      - run: pip install pylint
      - run: pip install pep8
      - run: pip install coveralls
      - run: pep8 --ignore=E501, E402 *.py gstack
      - run: pylint --rcfile=pylint.rc *.py ec2stack
      - run: nosetests --with-coverage --cover-erase --cover-package=ec2stack --cover-html   
      - run: coveralls       
 
              
