name: Build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          pip --use-mirrors install pylint
          pip --use-mirrors install pep8
          pip --use-mirrors install coveralls
          pip --use-mirrors install -e . --use-mirrors
      - name: Script
        run: |
           pep8 --ignore=E501, E402 *.py gstack
           pylint --rcfile=pylint.rc *.py ec2stack
           nosetests --with-coverage --cover-erase --cover-package=gstack
      - name: after_success
        run: coveralls
          
      
          
    
